### ISSUE TITLE
How to get version information?

### ISSUE THREAD

**Issue by mxmlnkn** [Rogdham/python-xz#1]
It would be nice if the module had a `__version__` member. I find that the easiest to use and many still support it.

I know that there is `importlib.metadata` but I find it to have many hurdles:
 - It requires Python 3.8. There is a backport but it requires trying two different imports and adds a new dependency for older Python versions. the dataclasses backport is easier to use because the name is interchangible.
 - It's hard to use. It requires the package name as distributed. But here the package name is `python-xz` as opposed to the module name which is just `xz`. I could not find a reliable way to get that name from the module. I tried `xz.__name__` and `xz.__package__`, which both return `xz`. Maybe there is some other way?

**Comment by Rogdham** [comment]
From my understanding, having `__version__` was a proposition in [PEP 396](https://www.python.org/dev/peps/pep-0396/) that is rejected, and you cannot rely on modules to provide `__version__`. Now the [`importlib.metadata`](https://docs.python.org/3/library/importlib.metadata.html) module seems the way to go.

> This PEP was formally rejected on 2021-04-14. The packaging ecosystem has changed significantly in the intervening years since this PEP was first written, and APIs such as importlib.metadata.versions() provide for a much better experience
> --- https://www.python.org/dev/peps/pep-0396/#pep-rejection

```python
>>> from importlib.metadata import version
>>> version('python-xz')
'0.1.1'
```

---

For older versions of Python, instead of the backport you can use `pkg_resources` if `setuptools` is installed:

```python
>>> from pkg_resources import get_distribution
>>> get_distribution('python-xz').version
'0.1.1'
```

> Use of pkg_resources is discouraged in favor of importlib.resources, importlib.metadata, and their backports (resources, metadata). Please consider using those libraries instead of pkg_resources.
> --- https://setuptools.readthedocs.io/en/latest/pkg_resources.html

---

> It requires the package name as distributed. 

That's a good point. Although one could argue that if you import a module, it means that it has been installed before, so you know the package name.

---

With all that being said, there may still be some value in getting the version from an imported module (and not from its distribution name), i.e. from `xz` after an `import xz`. Getting `xz.__version__` would solve this need.

I agree that although the PEP 396 is rejected, `__version__` is provided by many libraries.

So I will look into adding it :eyes:

**Comment by mxmlnkn** [comment]
Another point is that `importlib.metadata` only gets the version from the packaging system. If you do some funny module loading stuff you might get a different version than the module you have at runtime.

I also saw PEP 8 being mentioned in reference to `__version__` but there it is "only" mentioned as an example for module level dunder names.

I guess, I just like the ease of the old method and I would personally have preferred PEP 396 to pass. It feels like the shift to importlib.metadata puts the work to the user instead of the developer, which feels wrong assuming that there are many times more users than developers. But that would be a discussion for the Python mailing list if I had sufficient pushiness about this issue.

In the end, I only need it for debugging, so it wouldn't be all that problematic if it was missing. I already have a "hasattr" check in place if it is missing anyway.

Just, the problem with module name vs distribution name struck me as very problematic in comparison to using `__version__`.

Currently, my plan is to make python-xz the default requirement for ratarmount because I can't do it with lzmaffi because it depends on cffi, which will most likely be missing, meaning the pip installation will fail.

**Comment by Rogdham** [comment]
Version `0.1.2` now exports the version as the module attribute `__version__` :rocket:
