### ISSUE TITLE
Simple Extraction

### ISSUE THREAD

**Issue by freeload101** [Rogdham/python-xz#4]
Sorry I'm building a portable Android Pen testing Powershell script for Windows and I can't for the life of me get `frida-server-15.2.2-android-x86.xz` extracted... 7zip can extract it but I'm not looking to download yet another binary blob just for this xz file... Extracted it's a single ELF binary "frida-server-15.2.2-android-x86" Plz help...I can't find anything but this Python mod. My environment has Android Emulator running with Host running Java and Python. Everything else I can figure out but how to extract this xz file without installing 7zip....

```
import xz

with xz.open('frida-server-15.2.2-android-x86.xz') as f:
    print(f)
```

```
python 1.py
<XZFile object at 0x1044ab7aec>
```

Here is the project so far:
https://github.com/freeload101/Java-Android-Magisk-Burp-Objection-Root-Emulator-Easy

**Comment by Rogdham** [comment]
Hello @freeload101,

The `f` variable you get is a file-like object, so to get the data you should use the `.read` method:

```python
with xz.open('frida-server-15.2.2-android-x86.xz') as f:
    print(f.read(4))  # get the first 4 bytes, will print b'\x7fELF'
```

If you want to read it all into a variable, you can use `.read()` without specifying the number of bytes to read:


```python
with xz.open('frida-server-15.2.2-android-x86.xz') as f:
    data = f.read()

print(len(data))  # 46387888 (so 46MB)
```

If you want to decompress it into an other file, open the other file for writing (in binary mode) and use `shutil.copyfileobj`:

```python
import shutil

with xz.open('frida-server-15.2.2-android-x86.xz') as f:
    with open('frida-server.elf', 'wb') as fout:
        shutil.copyfileobj(f, fout)
```

Tell me if that works for you, or if you need more precise help achieving something please describe your use-case more precisely!

---

Also, I must mention that this library aims at filling the gaps in the XZ support of the standard library; if you are only interested in reading all data in one pass of that file, you may use the standard library directly by using `lzma` instead of `xz` in all my examples above.

**Comment by freeload101** [comment]
OMG THANK YOU SO MUCH!
