### ISSUE TITLE
Providing conda packages

### ISSUE THREAD

**Issue by ap--** [Rogdham/python-xz#5]
Hello @Rogdham 

I am starting work on providing conda packages for ratarmount and its dependencies.
Would you be interested in providing python-xz via conda?
If yes, I could offer to create the feedstock repository for you to provide packages via conda-forge. I would also be maintaining this feedstock repository, and (of course) add you as a maintainer too.

For reference, here's the discussion in the downstream repo: https://github.com/mxmlnkn/ratarmount/issues/99

Let me know what you think,
Cheers,
Andreas 😃

**Comment by Rogdham** [comment]
Hello @ap-- and thank you for your message, your offer, and your interest through ratarmount :wave:

I am not interested in providing python-xz via conda myself, nor maintaining such a distribution. Indeed, I am not currently a user of conda. And from experience it's better not to get involved into maintaining something you don't use :wink: 

With that being said, feel free to create the necessary wizardry to distribute python-xz on conda yourself! <sup>(it's not like I could prevent you from doing that anyway…)</sup> I would however appreciate if the conda distribution could indicate in some ways (metadata?) the following:
- That it's an unofficial distribution (i.e. you are the maintainer, I'm not);
- The upstream URL `https://github.com/Rogdham/python-xz` (mainly for end users to be able to report bugs easilly); this is already in the metadata of the package on PyPI if that's of any help.

Would that make any sense to you? Other thoughts that come to my mind:
- When a new version of python-xz is released, would you be automatically noticed so that the conda distribution is updated?
- Of course feel free to ask any questions you might have, or if you have some changes required in the python-xz package so that it's easier for you to distribute it on conda, I'm open to suggestions!

Regarding the last point, I feel like this issue would be the good place to discuss should the case arise, so I'm leaving it open as a result.

**Comment by ap--** [comment]
> And from experience it's better not to get involved into maintaining something you don't use 😉

100% agree 😄 

#### To address your points:

> That it's an unofficial distribution (i.e. you are the maintainer, I'm not);`

That works. conda-forge feedstocks list the maintainers. I will just not add you to that list then.

> The upstream URL https://github.com/Rogdham/python-xz (mainly for end users to be able to report bugs easilly);

Same here. In the conda-forge feedstock repository the upstream repository will be linked

> When a new version of python-xz is released, would you be automatically noticed so that the conda distribution is updated?

Yes, the conda eco-system runs bots that inform the maintainers once a new version of your tool lands on pypi.

> Of course feel free to ask any questions you might have, or if you have some changes required in the python-xz package so that it's easier for you to distribute it on conda, I'm open to suggestions!

Thanks, I'll see if I run into any issues, and will update you here.

Cheers,
Andreas 😃

**Comment by ap--** [comment]
Note to self: Staged Recipe https://github.com/conda-forge/staged-recipes/pull/21252

**Comment by ap--** [comment]
Hi @Rogdham,

the conda-forge package is now available.
If you're interested, [here](https://github.com/conda-forge/python-xz-feedstock) is the feedstock repository and (after setting up conda) you can install via conda with the following command:

```shell
conda install -c conda-forge python-xz
```

I'll maintain the package on conda-forge. Whenever you release a new version on pypi, I'll be notified via the conda-forge bot, so updated conda packages will be out as soon as I update the feedstock (usually within 1-3 days).

And here's the code for a shields.io badge in case you want to add it to the readme:
```
[![Conda (channel only)](https://img.shields.io/conda/vn/conda-forge/python-xz?label=conda)](https://anaconda.org/conda-forge/python-xz)
```

Cheers,
Andreas :smiley:

**Comment by Rogdham** [comment]
Terrific, thank you Andreas for your work!
